name: Auto Label Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  issues: write

jobs:
  auto-label-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Apply labels to PR
        uses: actions/github-script@v7

        with:
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;

            let labels = ['gssoc-2026'];

            if (branch.includes('docs/')) {
              labels.push('documentation');
            }

            if (branch.includes('feat/')) {
              labels.push('type:feature');
            }

            if (branch.includes('fix/')) {
              labels.push('type:bug');
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels
            });
